name: my_photo_filters
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.1
  image: ^4.1.6
  path_provider: ^2.1.3
  photo_manager: ^3.1.1
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  intl: ^0.19.0
  

flutter:
  uses-material-design: true
